# -*- coding: utf-8 -*-
"""HackberryPi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9658Vb2CuZ-cUDUdzzFSplgQ9kL2LLC
"""

import time
import requests
import os
from gpiozero import Button
from picamera2 import Picamera2
#sudo apt install espeak-- Run on command line
#https://www.dexterindustries.com/howto/make-your-raspberry-pi-speak/
import os

button = Button(17)

def delete_images(images):
    for img in images:
        os.remove(img)

def capture_image():

    filename = f"frame_{int(time.time())}.jpg"
    picam.capture_file(filename)

    return filename

def speak_feedback(text):
    os.system(f'espeak "{text}"')

while True:
    print("Waiting for button...")

    button.wait_for_press()

    print("Recording workout")

    images = capture_images()

    print("Sending to cloud")

    suggestion = send_to_cloud(images)

    delete_images(images)

    print("Feedback:", suggestion)

    speak_feedback(suggestion)